# Generated by Django 2.1.3 on 2018-11-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('typeid', models.IntegerField(blank=True)),
                ('bookname', models.CharField(blank=True, max_length=30)),
                ('author', models.CharField(blank=True, max_length=30)),
                ('publish', models.CharField(blank=True, max_length=30)),
                ('publishdate', models.DateField(blank=True)),
                ('publishtime', models.IntegerField(blank=True)),
                ('unitprice', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Booktype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('typename', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'booktype',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Borrowbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowdate', models.DateField(blank=True)),
                ('returndate', models.DateField(blank=True)),
                ('fine', models.IntegerField(blank=True)),
                ('iSBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Book')),
            ],
            options={
                'db_table': 'borrowbook',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('readerid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('type', models.IntegerField(blank=True)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField(blank=True)),
                ('sex', models.CharField(blank=True, max_length=4)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('dept', models.CharField(blank=True, max_length=20)),
                ('regdate', models.DateField(blank=True)),
            ],
            options={
                'db_table': 'reader',
            },
        ),
        migrations.CreateModel(
            name='Readertype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('typename', models.CharField(blank=True, max_length=20)),
                ('maxborrownum', models.IntegerField(blank=True)),
                ('limit', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'readertype',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='readerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Reader'),
        ),
        migrations.AlterUniqueTogether(
            name='borrowbook',
            unique_together={('readerId', 'iSBN')},
        ),
    ]
